[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/healthz"
port = 8080
timeout = 30
interval = 15
retries = 3

[[deploy.env]]
key = "BACKEND_URL"
value = "http://call-sentiment-analysis.railway.internal:8080"

[[deploy.env]]
key = "FLASK_ENV"
value = "production"

[[deploy.env]]
key = "PORT"
value = "8501"