[
build
]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[
deploy
]
startCommand = "./start.sh"
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.env]
BACKEND_URL = "http://call-sentiment-analysis.railway.internal:8080"

[
deploy.healthcheck
]
port = 8080
path = "/healthz"
timeout = 30