[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[deploy.env]]
key = "BACKEND_URL"
value = "http://call-sentiment-analysis.railway.internal:8080"